version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=spax
      - POSTGRES_PASSWORD=xaps
      - POSTGRES_DB=spax_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: